/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type NotFoundErrorRepData = {
  /**
   * Specific error code encountered
   */
  code: string;
  /**
   * Description of the error
   */
  message: string;
};

export class NotFoundErrorRep extends Error {
  /**
   * Specific error code encountered
   */
  code: string;

  /** The original data that was passed to this error instance. */
  data$: NotFoundErrorRepData;

  constructor(err: NotFoundErrorRepData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;

    this.name = "NotFoundErrorRep";
  }
}

/** @internal */
export const NotFoundErrorRep$inboundSchema: z.ZodType<
  NotFoundErrorRep,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
})
  .transform((v) => {
    return new NotFoundErrorRep(v);
  });

/** @internal */
export type NotFoundErrorRep$Outbound = {
  code: string;
  message: string;
};

/** @internal */
export const NotFoundErrorRep$outboundSchema: z.ZodType<
  NotFoundErrorRep$Outbound,
  z.ZodTypeDef,
  NotFoundErrorRep
> = z.instanceof(NotFoundErrorRep)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.string(),
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotFoundErrorRep$ {
  /** @deprecated use `NotFoundErrorRep$inboundSchema` instead. */
  export const inboundSchema = NotFoundErrorRep$inboundSchema;
  /** @deprecated use `NotFoundErrorRep$outboundSchema` instead. */
  export const outboundSchema = NotFoundErrorRep$outboundSchema;
  /** @deprecated use `NotFoundErrorRep$Outbound` instead. */
  export type Outbound = NotFoundErrorRep$Outbound;
}
