/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accessTokensPostToken } from "../../funcs/accessTokensPostToken.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.AccessTokenPost$inboundSchema,
};

export const tool$accessTokensPostToken: ToolDefinition<typeof args> = {
  name: "access-tokens-post-token",
  description: `Create access token

Create a new access token.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await accessTokensPostToken(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
