/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountUsageBetaGetMauUsageByCategory } from "../../funcs/accountUsageBetaGetMauUsageByCategory.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetMauUsageByCategoryRequest$inboundSchema,
};

export const tool$accountUsageBetaGetMauUsageByCategory: ToolDefinition<
  typeof args
> = {
  name: "account-usage-(beta)-get-mau-usage-by-category",
  description: `Get MAU usage by category

Get time-series arrays of the number of monthly active users (MAU) seen by LaunchDarkly from your account, broken down by the category of users. The category is either \`browser\`, \`mobile\`, or \`backend\`.<br/><br/>Endpoints for retrieving monthly active users (MAU) do not return information about active context instances. After you have upgraded your LaunchDarkly SDK to use contexts instead of users, you should not rely on this endpoint. To learn more, read [Account usage metrics](https://launchdarkly.com/docs/home/account/metrics).`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await accountUsageBetaGetMauUsageByCategory(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
