/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { aiConfigsBetaDeleteAIConfig } from "../../funcs/aiConfigsBetaDeleteAIConfig.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteAIConfigRequest$inboundSchema,
};

export const tool$aiConfigsBetaDeleteAIConfig: ToolDefinition<typeof args> = {
  name: "AI-configs-(beta)-delete-AI-config",
  description: `Delete AI Config

Delete an existing AI Config.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await aiConfigsBetaDeleteAIConfig(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
