/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { applicationsBetaGetApplications } from "../../funcs/applicationsBetaGetApplications.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApplicationsRequest$inboundSchema,
};

export const tool$applicationsBetaGetApplications: ToolDefinition<typeof args> =
  {
    name: "applications-(beta)-get-applications",
    description: `Get applications


Get a list of applications.

### Expanding the applications response

LaunchDarkly supports expanding the "Get applications" response to include additional fields.

To expand the response, append the \`expand\` query parameter and include the following:

* \`flags\` includes details on the flags that have been evaluated by the application

For example, use \`?expand=flags\` to include the \`flags\` field in the response. By default, this field is **not** included in the response.
`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await applicationsBetaGetApplications(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
