/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { approvalsDeleteApprovalRequestForFlag } from "../../funcs/approvalsDeleteApprovalRequestForFlag.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApprovalRequestForFlagRequest$inboundSchema,
};

export const tool$approvalsDeleteApprovalRequestForFlag: ToolDefinition<
  typeof args
> = {
  name: "approvals-delete-approval-request-for-flag",
  description: `Delete approval request for a flag

Delete an approval request for a feature flag.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await approvalsDeleteApprovalRequestForFlag(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
