/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { approvalsGetForFlag } from "../../funcs/approvalsGetForFlag.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApprovalForFlagRequest$inboundSchema,
};

export const tool$approvalsGetForFlag: ToolDefinition<typeof args> = {
  name: "get-flag-approval-request",
  description:
    `Retrieves details of a specific approval request for a feature flag, including its current status, reviewers, and the proposed changes. Allows agents to inspect pending changes before deciding to review or apply them.
`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await approvalsGetForFlag(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
