/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { codeReferencesDeleteRepository } from "../../funcs/codeReferencesDeleteRepository.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteRepositoryRequest$inboundSchema,
};

export const tool$codeReferencesDeleteRepository: ToolDefinition<typeof args> =
  {
    name: "code-references-delete-repository",
    description: `Delete repository

Delete a repository with the specified name.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await codeReferencesDeleteRepository(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(void 0, apiCall);
    },
  };
