/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { contextsPutContextKind } from "../../funcs/contextsPutContextKind.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PutContextKindRequest$inboundSchema,
};

export const tool$contextsPutContextKind: ToolDefinition<typeof args> = {
  name: "contexts-put-context-kind",
  description: `Create or update context kind

Create or update a context kind by key. Only the included fields will be updated.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await contextsPutContextKind(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
