/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { followFlagsGetFlagFollowers } from "../../funcs/followFlagsGetFlagFollowers.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetFlagFollowersRequest$inboundSchema,
};

export const tool$followFlagsGetFlagFollowers: ToolDefinition<typeof args> = {
  name: "follow-flags-get-flag-followers",
  description: `Get followers of a flag in a project and environment

Get a list of members following a flag in a project and environment`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await followFlagsGetFlagFollowers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
