/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { holdoutsBetaPostHoldout } from "../../funcs/holdoutsBetaPostHoldout.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostHoldoutRequest$inboundSchema,
};

export const tool$holdoutsBetaPostHoldout: ToolDefinition<typeof args> = {
  name: "holdouts-(beta)-post-holdout",
  description: `Create holdout

Create a new holdout in the specified project.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await holdoutsBetaPostHoldout(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
