/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { insightsScoresBetaGetInsightGroups } from "../../funcs/insightsScoresBetaGetInsightGroups.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetInsightGroupsRequest$inboundSchema,
};

export const tool$insightsScoresBetaGetInsightGroups: ToolDefinition<
  typeof args
> = {
  name: "insights-scores-(beta)-get-insight-groups",
  description: `List insight groups

List groups for which you are collecting insights

### Expanding the insight groups collection response

LaunchDarkly supports expanding the insight groups collection response to include additional fields.

To expand the response, append the \`expand\` query parameter and include the following:

* \`scores\` includes details on all of the scores used in the engineering insights metrics views for each group
* \`environment\` includes details on each environment associated with each group
* \`metadata\` includes counts of the number of insight groups with particular indicators, such as "excellent," "good," "fair," and so on.

For example, use \`?expand=scores\` to include the \`scores\` field in the response. By default, this field is **not** included in the response.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await insightsScoresBetaGetInsightGroups(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
