/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { insightsScoresBetaGetInsightGroup } from "../../funcs/insightsScoresBetaGetInsightGroup.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetInsightGroupRequest$inboundSchema,
};

export const tool$insightsScoresBetaGetInsightGroup: ToolDefinition<
  typeof args
> = {
  name: "insights-scores-(beta)-get-insight-group",
  description: `Get insight group

Get insight group

### Expanding the insight group response

LaunchDarkly supports expanding the insight group response to include additional fields.

To expand the response, append the \`expand\` query parameter and include the following:

* \`scores\` includes details on all of the scores used in the engineering insights metrics views for this group
* \`environment\` includes details on each environment associated with this group

For example, use \`?expand=scores\` to include the \`scores\` field in the response. By default, this field is **not** included in the response.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await insightsScoresBetaGetInsightGroup(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
