/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsBetaCreateIntegrationConfiguration } from "../../funcs/integrationsBetaCreateIntegrationConfiguration.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateIntegrationConfigurationRequest$inboundSchema,
};

export const tool$integrationsBetaCreateIntegrationConfiguration:
  ToolDefinition<typeof args> = {
    name: "integrations-(beta)-create-integration-configuration",
    description: `Create integration configuration

Create a new integration configuration. (Excludes [persistent store](https://launchdarkly.com/docs/api/persistent-store-integrations-beta) and [flag import configurations](https://launchdarkly.com/docs/api/flag-import-configurations-beta).)`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await integrationsBetaCreateIntegrationConfiguration(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
