/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metricsDeleteMetric } from "../../funcs/metricsDeleteMetric.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteMetricRequest$inboundSchema,
};

export const tool$metricsDeleteMetric: ToolDefinition<typeof args> = {
  name: "metrics-delete-metric",
  description: `Delete metric

Delete a metric by key.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metricsDeleteMetric(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
