/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metricsBetaGetMetricGroup } from "../../funcs/metricsBetaGetMetricGroup.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetMetricGroupRequest$inboundSchema,
};

export const tool$metricsBetaGetMetricGroup: ToolDefinition<typeof args> = {
  name: "metrics-(beta)-get-metric-group",
  description: `Get metric group

Get information for a single metric group from the specific project.

### Expanding the metric group response
LaunchDarkly supports two fields for expanding the "Get metric group" response. By default, these fields are **not** included in the response.

To expand the response, append the \`expand\` query parameter and add a comma-separated list with either or both of the following fields:

- \`experiments\` includes all experiments from the specific project that use the metric group
- \`experimentCount\` includes the number of experiments from the specific project that use the metric group

For example, \`expand=experiments\` includes the \`experiments\` field in the response.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metricsBetaGetMetricGroup(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
