/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { otherGetCallerIdentity } from "../../funcs/otherGetCallerIdentity.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$otherGetCallerIdentity: ToolDefinition = {
  name: "other-get-caller-identity",
  description: `Identify the caller

Get basic information about the identity used (session cookie, API token, SDK keys, etc.) to call the API`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await otherGetCallerIdentity(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
