/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { persistentStoreIntegrationsBetaPatchBigSegmentStoreIntegration } from "../../funcs/persistentStoreIntegrationsBetaPatchBigSegmentStoreIntegration.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PatchBigSegmentStoreIntegrationRequest$inboundSchema,
};

export const tool$persistentStoreIntegrationsBetaPatchBigSegmentStoreIntegration:
  ToolDefinition<typeof args> = {
    name:
      "persistent-store-integrations-(beta)-patch-big-segment-store-integration",
    description: `Update big segment store integration

Update a big segment store integration. Updating a big segment store requires a [JSON Patch](https://datatracker.ietf.org/doc/html/rfc6902) representation of the desired changes. To learn more, read [Updates](https://launchdarkly.com/docs/api#updates).`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await persistentStoreIntegrationsBetaPatchBigSegmentStoreIntegration(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
