/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { relayProxyConfigurationsPatchRelayAutoConfig } from "../../funcs/relayProxyConfigurationsPatchRelayAutoConfig.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PatchRelayAutoConfigRequest$inboundSchema,
};

export const tool$relayProxyConfigurationsPatchRelayAutoConfig: ToolDefinition<
  typeof args
> = {
  name: "relay-proxy-configurations-patch-relay-auto-config",
  description: `Update a Relay Proxy config

Update a Relay Proxy configuration. Updating a configuration uses a [JSON patch](https://datatracker.ietf.org/doc/html/rfc6902) or [JSON merge patch](https://datatracker.ietf.org/doc/html/rfc7386) representation of the desired changes. To learn more, read [Updates](https://launchdarkly.com/docs/api#updates).`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] =
      await relayProxyConfigurationsPatchRelayAutoConfig(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
