/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { releasePipelinesBetaGetAllReleaseProgressionsForReleasePipeline } from "../../funcs/releasePipelinesBetaGetAllReleaseProgressionsForReleasePipeline.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.GetAllReleaseProgressionsForReleasePipelineRequest$inboundSchema,
};

export const tool$releasePipelinesBetaGetAllReleaseProgressionsForReleasePipeline:
  ToolDefinition<typeof args> = {
    name:
      "release-pipelines-(beta)-get-all-release-progressions-for-release-pipeline",
    description: `Get release progressions for release pipeline

Get details on the progression of all releases, across all flags, for a release pipeline`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await releasePipelinesBetaGetAllReleaseProgressionsForReleasePipeline(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
