/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksDeleteWebhook } from "../../funcs/webhooksDeleteWebhook.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteWebhookRequest$inboundSchema,
};

export const tool$webhooksDeleteWebhook: ToolDefinition<typeof args> = {
  name: "webhooks-delete-webhook",
  description: `Delete webhook

Delete a webhook by ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooksDeleteWebhook(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
