/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workflowTemplatesGetWorkflowTemplates } from "../../funcs/workflowTemplatesGetWorkflowTemplates.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetWorkflowTemplatesRequest$inboundSchema,
};

export const tool$workflowTemplatesGetWorkflowTemplates: ToolDefinition<
  typeof args
> = {
  name: "workflow-templates-get-workflow-templates",
  description: `Get workflow templates

Get workflow templates belonging to an account, or can optionally return templates_endpoints.workflowTemplateSummariesListingOutputRep when summary query param is true`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workflowTemplatesGetWorkflowTemplates(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
