/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { codeReferencesGetStatistics } from "../funcs/codeReferencesGetStatistics.js";
import { codeReferencesListExtinctions } from "../funcs/codeReferencesListExtinctions.js";
import { codeReferencesListRepositories } from "../funcs/codeReferencesListRepositories.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CodeReferences extends ClientSDK {
  /**
   * List extinctions
   *
   * @remarks
   * Get a list of all extinctions. LaunchDarkly creates an extinction event after you remove all code references to a flag. To learn more, read [About extinction events](https://launchdarkly.com/docs/home/observability/code-references#about-extinction-events).
   */
  async listExtinctions(
    request: operations.GetExtinctionsRequest,
    options?: RequestOptions,
  ): Promise<components.ExtinctionCollectionRep> {
    return unwrapAsync(codeReferencesListExtinctions(
      this,
      request,
      options,
    ));
  }

  /**
   * List repositories
   *
   * @remarks
   * Get a list of connected repositories. Optionally, you can include branch metadata with the `withBranches` query parameter. Embed references for the default branch with `ReferencesForDefaultBranch`. You can also filter the list of code references by project key and flag key.
   */
  async listRepositories(
    request: operations.GetRepositoriesRequest,
    options?: RequestOptions,
  ): Promise<components.RepositoryCollectionRep> {
    return unwrapAsync(codeReferencesListRepositories(
      this,
      request,
      options,
    ));
  }

  /**
   * Get code references statistics for flags
   *
   * @remarks
   * Get statistics about all the code references across repositories for all flags in your project that have code references in the default branch, for example, `main`. Optionally, you can include the `flagKey` query parameter to limit your request to statistics about code references for a single flag. This endpoint returns the number of references to your flag keys in your repositories, as well as a link to each repository.
   */
  async getStatistics(
    request: operations.GetStatisticsRequest,
    options?: RequestOptions,
  ): Promise<components.StatisticCollectionRep> {
    return unwrapAsync(codeReferencesGetStatistics(
      this,
      request,
      options,
    ));
  }
}
