/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { releasePipelinesBetaDeleteReleasePipeline } from "../funcs/releasePipelinesBetaDeleteReleasePipeline.js";
import { releasePipelinesBetaGetAllReleasePipelines } from "../funcs/releasePipelinesBetaGetAllReleasePipelines.js";
import { releasePipelinesBetaGetAllReleaseProgressionsForReleasePipeline } from "../funcs/releasePipelinesBetaGetAllReleaseProgressionsForReleasePipeline.js";
import { releasePipelinesBetaGetReleasePipelineByKey } from "../funcs/releasePipelinesBetaGetReleasePipelineByKey.js";
import { releasePipelinesBetaPostReleasePipeline } from "../funcs/releasePipelinesBetaPostReleasePipeline.js";
import { releasePipelinesBetaPutReleasePipeline } from "../funcs/releasePipelinesBetaPutReleasePipeline.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ReleasePipelinesBeta extends ClientSDK {
  /**
   * Get all release pipelines
   *
   * @remarks
   * Get all release pipelines for a project.
   *
   * ### Filtering release pipelines
   *
   * LaunchDarkly supports the following fields for filters:
   *
   * - `query` is a string that matches against the release pipeline `key`, `name`, and `description`. It is not case sensitive. For example: `?filter=query:examplePipeline`.
   *
   * - `env` is a string that matches an environment key. For example: `?filter=env:production`.
   */
  async getAllReleasePipelines(
    request: operations.GetAllReleasePipelinesRequest,
    options?: RequestOptions,
  ): Promise<models.ReleasePipelineCollection> {
    return unwrapAsync(releasePipelinesBetaGetAllReleasePipelines(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a release pipeline
   *
   * @remarks
   * Creates a new release pipeline.
   *
   * The first release pipeline you create is automatically set as the default release pipeline for your project. To change the default release pipeline, use the [Update project](https://launchdarkly.com/docs/ld-docs/api/projects/patch-project) API to set the `defaultReleasePipelineKey`.
   *
   * You can create up to 20 release pipelines per project.
   */
  async postReleasePipeline(
    request: operations.PostReleasePipelineRequest,
    options?: RequestOptions,
  ): Promise<models.ReleasePipeline> {
    return unwrapAsync(releasePipelinesBetaPostReleasePipeline(
      this,
      request,
      options,
    ));
  }

  /**
   * Get release pipeline by key
   *
   * @remarks
   * Get a release pipeline by key
   */
  async getReleasePipelineByKey(
    request: operations.GetReleasePipelineByKeyRequest,
    options?: RequestOptions,
  ): Promise<models.ReleasePipeline> {
    return unwrapAsync(releasePipelinesBetaGetReleasePipelineByKey(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a release pipeline
   *
   * @remarks
   * Updates a release pipeline.
   */
  async putReleasePipeline(
    request: operations.PutReleasePipelineRequest,
    options?: RequestOptions,
  ): Promise<models.ReleasePipeline> {
    return unwrapAsync(releasePipelinesBetaPutReleasePipeline(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete release pipeline
   *
   * @remarks
   * Deletes a release pipeline.
   *
   * You cannot delete the default release pipeline.
   *
   * If you want to delete a release pipeline that is currently the default, create a second release pipeline and set it as the default. Then delete the first release pipeline. To change the default release pipeline, use the [Update project](https://launchdarkly.com/docs/ld-docs/api/projects/patch-project) API to set the `defaultReleasePipelineKey`.
   */
  async deleteReleasePipeline(
    request: operations.DeleteReleasePipelineRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(releasePipelinesBetaDeleteReleasePipeline(
      this,
      request,
      options,
    ));
  }

  /**
   * Get release progressions for release pipeline
   *
   * @remarks
   * Get details on the progression of all releases, across all flags, for a release pipeline
   */
  async getAllReleaseProgressionsForReleasePipeline(
    request: operations.GetAllReleaseProgressionsForReleasePipelineRequest,
    options?: RequestOptions,
  ): Promise<models.ReleaseProgressionCollection> {
    return unwrapAsync(
      releasePipelinesBetaGetAllReleaseProgressionsForReleasePipeline(
        this,
        request,
        options,
      ),
    );
  }
}
