/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateBigSegmentExportRequest = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * The segment key
   */
  segmentKey: string;
};

/** @internal */
export const CreateBigSegmentExportRequest$inboundSchema: z.ZodType<
  CreateBigSegmentExportRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectKey: z.string(),
  environmentKey: z.string(),
  segmentKey: z.string(),
});

/** @internal */
export type CreateBigSegmentExportRequest$Outbound = {
  projectKey: string;
  environmentKey: string;
  segmentKey: string;
};

/** @internal */
export const CreateBigSegmentExportRequest$outboundSchema: z.ZodType<
  CreateBigSegmentExportRequest$Outbound,
  z.ZodTypeDef,
  CreateBigSegmentExportRequest
> = z.object({
  projectKey: z.string(),
  environmentKey: z.string(),
  segmentKey: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateBigSegmentExportRequest$ {
  /** @deprecated use `CreateBigSegmentExportRequest$inboundSchema` instead. */
  export const inboundSchema = CreateBigSegmentExportRequest$inboundSchema;
  /** @deprecated use `CreateBigSegmentExportRequest$outboundSchema` instead. */
  export const outboundSchema = CreateBigSegmentExportRequest$outboundSchema;
  /** @deprecated use `CreateBigSegmentExportRequest$Outbound` instead. */
  export type Outbound = CreateBigSegmentExportRequest$Outbound;
}

export function createBigSegmentExportRequestToJSON(
  createBigSegmentExportRequest: CreateBigSegmentExportRequest,
): string {
  return JSON.stringify(
    CreateBigSegmentExportRequest$outboundSchema.parse(
      createBigSegmentExportRequest,
    ),
  );
}

export function createBigSegmentExportRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateBigSegmentExportRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBigSegmentExportRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBigSegmentExportRequest' from JSON`,
  );
}
