/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteAIConfigRequest = {
  projectKey: string;
  configKey: string;
};

/** @internal */
export const DeleteAIConfigRequest$inboundSchema: z.ZodType<
  DeleteAIConfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectKey: z.string(),
  configKey: z.string(),
});

/** @internal */
export type DeleteAIConfigRequest$Outbound = {
  projectKey: string;
  configKey: string;
};

/** @internal */
export const DeleteAIConfigRequest$outboundSchema: z.ZodType<
  DeleteAIConfigRequest$Outbound,
  z.ZodTypeDef,
  DeleteAIConfigRequest
> = z.object({
  projectKey: z.string(),
  configKey: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteAIConfigRequest$ {
  /** @deprecated use `DeleteAIConfigRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteAIConfigRequest$inboundSchema;
  /** @deprecated use `DeleteAIConfigRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteAIConfigRequest$outboundSchema;
  /** @deprecated use `DeleteAIConfigRequest$Outbound` instead. */
  export type Outbound = DeleteAIConfigRequest$Outbound;
}

export function deleteAIConfigRequestToJSON(
  deleteAIConfigRequest: DeleteAIConfigRequest,
): string {
  return JSON.stringify(
    DeleteAIConfigRequest$outboundSchema.parse(deleteAIConfigRequest),
  );
}

export function deleteAIConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteAIConfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteAIConfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteAIConfigRequest' from JSON`,
  );
}
