/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteApprovalRequestForFlagRequest = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The feature flag key
   */
  featureFlagKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * The feature flag approval request ID
   */
  id: string;
};

/** @internal */
export const DeleteApprovalRequestForFlagRequest$inboundSchema: z.ZodType<
  DeleteApprovalRequestForFlagRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectKey: z.string(),
  featureFlagKey: z.string(),
  environmentKey: z.string(),
  id: z.string(),
});

/** @internal */
export type DeleteApprovalRequestForFlagRequest$Outbound = {
  projectKey: string;
  featureFlagKey: string;
  environmentKey: string;
  id: string;
};

/** @internal */
export const DeleteApprovalRequestForFlagRequest$outboundSchema: z.ZodType<
  DeleteApprovalRequestForFlagRequest$Outbound,
  z.ZodTypeDef,
  DeleteApprovalRequestForFlagRequest
> = z.object({
  projectKey: z.string(),
  featureFlagKey: z.string(),
  environmentKey: z.string(),
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApprovalRequestForFlagRequest$ {
  /** @deprecated use `DeleteApprovalRequestForFlagRequest$inboundSchema` instead. */
  export const inboundSchema =
    DeleteApprovalRequestForFlagRequest$inboundSchema;
  /** @deprecated use `DeleteApprovalRequestForFlagRequest$outboundSchema` instead. */
  export const outboundSchema =
    DeleteApprovalRequestForFlagRequest$outboundSchema;
  /** @deprecated use `DeleteApprovalRequestForFlagRequest$Outbound` instead. */
  export type Outbound = DeleteApprovalRequestForFlagRequest$Outbound;
}

export function deleteApprovalRequestForFlagRequestToJSON(
  deleteApprovalRequestForFlagRequest: DeleteApprovalRequestForFlagRequest,
): string {
  return JSON.stringify(
    DeleteApprovalRequestForFlagRequest$outboundSchema.parse(
      deleteApprovalRequestForFlagRequest,
    ),
  );
}

export function deleteApprovalRequestForFlagRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApprovalRequestForFlagRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteApprovalRequestForFlagRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApprovalRequestForFlagRequest' from JSON`,
  );
}
