/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteApprovalRequestRequest = {
  /**
   * The approval request ID
   */
  id: string;
};

/** @internal */
export const DeleteApprovalRequestRequest$inboundSchema: z.ZodType<
  DeleteApprovalRequestRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteApprovalRequestRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteApprovalRequestRequest$outboundSchema: z.ZodType<
  DeleteApprovalRequestRequest$Outbound,
  z.ZodTypeDef,
  DeleteApprovalRequestRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApprovalRequestRequest$ {
  /** @deprecated use `DeleteApprovalRequestRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteApprovalRequestRequest$inboundSchema;
  /** @deprecated use `DeleteApprovalRequestRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteApprovalRequestRequest$outboundSchema;
  /** @deprecated use `DeleteApprovalRequestRequest$Outbound` instead. */
  export type Outbound = DeleteApprovalRequestRequest$Outbound;
}

export function deleteApprovalRequestRequestToJSON(
  deleteApprovalRequestRequest: DeleteApprovalRequestRequest,
): string {
  return JSON.stringify(
    DeleteApprovalRequestRequest$outboundSchema.parse(
      deleteApprovalRequestRequest,
    ),
  );
}

export function deleteApprovalRequestRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApprovalRequestRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteApprovalRequestRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApprovalRequestRequest' from JSON`,
  );
}
