/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteReleaseByFlagKeyRequest = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The flag key
   */
  flagKey: string;
};

/** @internal */
export const DeleteReleaseByFlagKeyRequest$inboundSchema: z.ZodType<
  DeleteReleaseByFlagKeyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectKey: z.string(),
  flagKey: z.string(),
});

/** @internal */
export type DeleteReleaseByFlagKeyRequest$Outbound = {
  projectKey: string;
  flagKey: string;
};

/** @internal */
export const DeleteReleaseByFlagKeyRequest$outboundSchema: z.ZodType<
  DeleteReleaseByFlagKeyRequest$Outbound,
  z.ZodTypeDef,
  DeleteReleaseByFlagKeyRequest
> = z.object({
  projectKey: z.string(),
  flagKey: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteReleaseByFlagKeyRequest$ {
  /** @deprecated use `DeleteReleaseByFlagKeyRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteReleaseByFlagKeyRequest$inboundSchema;
  /** @deprecated use `DeleteReleaseByFlagKeyRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteReleaseByFlagKeyRequest$outboundSchema;
  /** @deprecated use `DeleteReleaseByFlagKeyRequest$Outbound` instead. */
  export type Outbound = DeleteReleaseByFlagKeyRequest$Outbound;
}

export function deleteReleaseByFlagKeyRequestToJSON(
  deleteReleaseByFlagKeyRequest: DeleteReleaseByFlagKeyRequest,
): string {
  return JSON.stringify(
    DeleteReleaseByFlagKeyRequest$outboundSchema.parse(
      deleteReleaseByFlagKeyRequest,
    ),
  );
}

export function deleteReleaseByFlagKeyRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteReleaseByFlagKeyRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteReleaseByFlagKeyRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteReleaseByFlagKeyRequest' from JSON`,
  );
}
