/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteTokenRequest = {
  /**
   * The ID of the access token to update
   */
  id: string;
};

/** @internal */
export const DeleteTokenRequest$inboundSchema: z.ZodType<
  DeleteTokenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteTokenRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteTokenRequest$outboundSchema: z.ZodType<
  DeleteTokenRequest$Outbound,
  z.ZodTypeDef,
  DeleteTokenRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteTokenRequest$ {
  /** @deprecated use `DeleteTokenRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteTokenRequest$inboundSchema;
  /** @deprecated use `DeleteTokenRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteTokenRequest$outboundSchema;
  /** @deprecated use `DeleteTokenRequest$Outbound` instead. */
  export type Outbound = DeleteTokenRequest$Outbound;
}

export function deleteTokenRequestToJSON(
  deleteTokenRequest: DeleteTokenRequest,
): string {
  return JSON.stringify(
    DeleteTokenRequest$outboundSchema.parse(deleteTokenRequest),
  );
}

export function deleteTokenRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteTokenRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteTokenRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteTokenRequest' from JSON`,
  );
}
