/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteWorkflowTemplateRequest = {
  /**
   * The template key
   */
  templateKey: string;
};

/** @internal */
export const DeleteWorkflowTemplateRequest$inboundSchema: z.ZodType<
  DeleteWorkflowTemplateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  templateKey: z.string(),
});

/** @internal */
export type DeleteWorkflowTemplateRequest$Outbound = {
  templateKey: string;
};

/** @internal */
export const DeleteWorkflowTemplateRequest$outboundSchema: z.ZodType<
  DeleteWorkflowTemplateRequest$Outbound,
  z.ZodTypeDef,
  DeleteWorkflowTemplateRequest
> = z.object({
  templateKey: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteWorkflowTemplateRequest$ {
  /** @deprecated use `DeleteWorkflowTemplateRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteWorkflowTemplateRequest$inboundSchema;
  /** @deprecated use `DeleteWorkflowTemplateRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteWorkflowTemplateRequest$outboundSchema;
  /** @deprecated use `DeleteWorkflowTemplateRequest$Outbound` instead. */
  export type Outbound = DeleteWorkflowTemplateRequest$Outbound;
}

export function deleteWorkflowTemplateRequestToJSON(
  deleteWorkflowTemplateRequest: DeleteWorkflowTemplateRequest,
): string {
  return JSON.stringify(
    DeleteWorkflowTemplateRequest$outboundSchema.parse(
      deleteWorkflowTemplateRequest,
    ),
  );
}

export function deleteWorkflowTemplateRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteWorkflowTemplateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteWorkflowTemplateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteWorkflowTemplateRequest' from JSON`,
  );
}
