/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApprovalForFlagRequest = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The feature flag key
   */
  featureFlagKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * The feature flag approval request ID
   */
  id: string;
};

/** @internal */
export const GetApprovalForFlagRequest$inboundSchema: z.ZodType<
  GetApprovalForFlagRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectKey: z.string(),
  featureFlagKey: z.string(),
  environmentKey: z.string(),
  id: z.string(),
});

/** @internal */
export type GetApprovalForFlagRequest$Outbound = {
  projectKey: string;
  featureFlagKey: string;
  environmentKey: string;
  id: string;
};

/** @internal */
export const GetApprovalForFlagRequest$outboundSchema: z.ZodType<
  GetApprovalForFlagRequest$Outbound,
  z.ZodTypeDef,
  GetApprovalForFlagRequest
> = z.object({
  projectKey: z.string(),
  featureFlagKey: z.string(),
  environmentKey: z.string(),
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApprovalForFlagRequest$ {
  /** @deprecated use `GetApprovalForFlagRequest$inboundSchema` instead. */
  export const inboundSchema = GetApprovalForFlagRequest$inboundSchema;
  /** @deprecated use `GetApprovalForFlagRequest$outboundSchema` instead. */
  export const outboundSchema = GetApprovalForFlagRequest$outboundSchema;
  /** @deprecated use `GetApprovalForFlagRequest$Outbound` instead. */
  export type Outbound = GetApprovalForFlagRequest$Outbound;
}

export function getApprovalForFlagRequestToJSON(
  getApprovalForFlagRequest: GetApprovalForFlagRequest,
): string {
  return JSON.stringify(
    GetApprovalForFlagRequest$outboundSchema.parse(getApprovalForFlagRequest),
  );
}

export function getApprovalForFlagRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApprovalForFlagRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApprovalForFlagRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApprovalForFlagRequest' from JSON`,
  );
}
