/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAIConfigVariationRequest = {
  projectKey: string;
  configKey: string;
  variationKey: string;
};

/** @internal */
export const GetAIConfigVariationRequest$inboundSchema: z.ZodType<
  GetAIConfigVariationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectKey: z.string(),
  configKey: z.string(),
  variationKey: z.string(),
});

/** @internal */
export type GetAIConfigVariationRequest$Outbound = {
  projectKey: string;
  configKey: string;
  variationKey: string;
};

/** @internal */
export const GetAIConfigVariationRequest$outboundSchema: z.ZodType<
  GetAIConfigVariationRequest$Outbound,
  z.ZodTypeDef,
  GetAIConfigVariationRequest
> = z.object({
  projectKey: z.string(),
  configKey: z.string(),
  variationKey: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAIConfigVariationRequest$ {
  /** @deprecated use `GetAIConfigVariationRequest$inboundSchema` instead. */
  export const inboundSchema = GetAIConfigVariationRequest$inboundSchema;
  /** @deprecated use `GetAIConfigVariationRequest$outboundSchema` instead. */
  export const outboundSchema = GetAIConfigVariationRequest$outboundSchema;
  /** @deprecated use `GetAIConfigVariationRequest$Outbound` instead. */
  export type Outbound = GetAIConfigVariationRequest$Outbound;
}

export function getAIConfigVariationRequestToJSON(
  getAIConfigVariationRequest: GetAIConfigVariationRequest,
): string {
  return JSON.stringify(
    GetAIConfigVariationRequest$outboundSchema.parse(
      getAIConfigVariationRequest,
    ),
  );
}

export function getAIConfigVariationRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAIConfigVariationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAIConfigVariationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAIConfigVariationRequest' from JSON`,
  );
}
