/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetBranchesRequest = {
  /**
   * The repository name
   */
  repo: string;
};

/** @internal */
export const GetBranchesRequest$inboundSchema: z.ZodType<
  GetBranchesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  repo: z.string(),
});

/** @internal */
export type GetBranchesRequest$Outbound = {
  repo: string;
};

/** @internal */
export const GetBranchesRequest$outboundSchema: z.ZodType<
  GetBranchesRequest$Outbound,
  z.ZodTypeDef,
  GetBranchesRequest
> = z.object({
  repo: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBranchesRequest$ {
  /** @deprecated use `GetBranchesRequest$inboundSchema` instead. */
  export const inboundSchema = GetBranchesRequest$inboundSchema;
  /** @deprecated use `GetBranchesRequest$outboundSchema` instead. */
  export const outboundSchema = GetBranchesRequest$outboundSchema;
  /** @deprecated use `GetBranchesRequest$Outbound` instead. */
  export type Outbound = GetBranchesRequest$Outbound;
}

export function getBranchesRequestToJSON(
  getBranchesRequest: GetBranchesRequest,
): string {
  return JSON.stringify(
    GetBranchesRequest$outboundSchema.parse(getBranchesRequest),
  );
}

export function getBranchesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetBranchesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBranchesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBranchesRequest' from JSON`,
  );
}
