/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetContextInstancesRequest = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * The context instance ID
   */
  id: string;
  /**
   * Specifies the maximum number of context instances to return (max: 50, default: 20)
   */
  limit?: number | undefined;
  /**
   * Limits results to context instances with sort values after the value specified. You can use this for pagination, however, we recommend using the `next` link we provide instead.
   */
  continuationToken?: string | undefined;
  /**
   * Specifies a field by which to sort. LaunchDarkly supports sorting by timestamp in ascending order by specifying `ts` for this value, or descending order by specifying `-ts`.
   */
  sort?: string | undefined;
  /**
   * A comma-separated list of context filters. This endpoint only accepts an `applicationId` filter. To learn more about the filter syntax, read [Filtering contexts and context instances](https://launchdarkly.com/docs/ld-docs/api/contexts#filtering-contexts-and-context-instances).
   */
  filter?: string | undefined;
  /**
   * Specifies whether to include or omit the total count of matching context instances. Defaults to true.
   */
  includeTotalCount?: boolean | undefined;
};

/** @internal */
export const GetContextInstancesRequest$inboundSchema: z.ZodType<
  GetContextInstancesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectKey: z.string(),
  environmentKey: z.string(),
  id: z.string(),
  limit: z.number().int().optional(),
  continuationToken: z.string().optional(),
  sort: z.string().optional(),
  filter: z.string().optional(),
  includeTotalCount: z.boolean().optional(),
});

/** @internal */
export type GetContextInstancesRequest$Outbound = {
  projectKey: string;
  environmentKey: string;
  id: string;
  limit?: number | undefined;
  continuationToken?: string | undefined;
  sort?: string | undefined;
  filter?: string | undefined;
  includeTotalCount?: boolean | undefined;
};

/** @internal */
export const GetContextInstancesRequest$outboundSchema: z.ZodType<
  GetContextInstancesRequest$Outbound,
  z.ZodTypeDef,
  GetContextInstancesRequest
> = z.object({
  projectKey: z.string(),
  environmentKey: z.string(),
  id: z.string(),
  limit: z.number().int().optional(),
  continuationToken: z.string().optional(),
  sort: z.string().optional(),
  filter: z.string().optional(),
  includeTotalCount: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetContextInstancesRequest$ {
  /** @deprecated use `GetContextInstancesRequest$inboundSchema` instead. */
  export const inboundSchema = GetContextInstancesRequest$inboundSchema;
  /** @deprecated use `GetContextInstancesRequest$outboundSchema` instead. */
  export const outboundSchema = GetContextInstancesRequest$outboundSchema;
  /** @deprecated use `GetContextInstancesRequest$Outbound` instead. */
  export type Outbound = GetContextInstancesRequest$Outbound;
}

export function getContextInstancesRequestToJSON(
  getContextInstancesRequest: GetContextInstancesRequest,
): string {
  return JSON.stringify(
    GetContextInstancesRequest$outboundSchema.parse(getContextInstancesRequest),
  );
}

export function getContextInstancesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetContextInstancesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetContextInstancesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetContextInstancesRequest' from JSON`,
  );
}
