/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetHoldoutByIdRequest = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * The holdout experiment ID
   */
  holdoutId: string;
};

/** @internal */
export const GetHoldoutByIdRequest$inboundSchema: z.ZodType<
  GetHoldoutByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectKey: z.string(),
  environmentKey: z.string(),
  holdoutId: z.string(),
});

/** @internal */
export type GetHoldoutByIdRequest$Outbound = {
  projectKey: string;
  environmentKey: string;
  holdoutId: string;
};

/** @internal */
export const GetHoldoutByIdRequest$outboundSchema: z.ZodType<
  GetHoldoutByIdRequest$Outbound,
  z.ZodTypeDef,
  GetHoldoutByIdRequest
> = z.object({
  projectKey: z.string(),
  environmentKey: z.string(),
  holdoutId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetHoldoutByIdRequest$ {
  /** @deprecated use `GetHoldoutByIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetHoldoutByIdRequest$inboundSchema;
  /** @deprecated use `GetHoldoutByIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetHoldoutByIdRequest$outboundSchema;
  /** @deprecated use `GetHoldoutByIdRequest$Outbound` instead. */
  export type Outbound = GetHoldoutByIdRequest$Outbound;
}

export function getHoldoutByIdRequestToJSON(
  getHoldoutByIdRequest: GetHoldoutByIdRequest,
): string {
  return JSON.stringify(
    GetHoldoutByIdRequest$outboundSchema.parse(getHoldoutByIdRequest),
  );
}

export function getHoldoutByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetHoldoutByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetHoldoutByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHoldoutByIdRequest' from JSON`,
  );
}
