/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetTriggerWorkflowByIdRequest = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The feature flag key
   */
  featureFlagKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * The flag trigger ID
   */
  id: string;
};

/** @internal */
export const GetTriggerWorkflowByIdRequest$inboundSchema: z.ZodType<
  GetTriggerWorkflowByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectKey: z.string(),
  featureFlagKey: z.string(),
  environmentKey: z.string(),
  id: z.string(),
});

/** @internal */
export type GetTriggerWorkflowByIdRequest$Outbound = {
  projectKey: string;
  featureFlagKey: string;
  environmentKey: string;
  id: string;
};

/** @internal */
export const GetTriggerWorkflowByIdRequest$outboundSchema: z.ZodType<
  GetTriggerWorkflowByIdRequest$Outbound,
  z.ZodTypeDef,
  GetTriggerWorkflowByIdRequest
> = z.object({
  projectKey: z.string(),
  featureFlagKey: z.string(),
  environmentKey: z.string(),
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTriggerWorkflowByIdRequest$ {
  /** @deprecated use `GetTriggerWorkflowByIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetTriggerWorkflowByIdRequest$inboundSchema;
  /** @deprecated use `GetTriggerWorkflowByIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetTriggerWorkflowByIdRequest$outboundSchema;
  /** @deprecated use `GetTriggerWorkflowByIdRequest$Outbound` instead. */
  export type Outbound = GetTriggerWorkflowByIdRequest$Outbound;
}

export function getTriggerWorkflowByIdRequestToJSON(
  getTriggerWorkflowByIdRequest: GetTriggerWorkflowByIdRequest,
): string {
  return JSON.stringify(
    GetTriggerWorkflowByIdRequest$outboundSchema.parse(
      getTriggerWorkflowByIdRequest,
    ),
  );
}

export function getTriggerWorkflowByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetTriggerWorkflowByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTriggerWorkflowByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTriggerWorkflowByIdRequest' from JSON`,
  );
}
