/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetUserFlagSettingRequest = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * The user key
   */
  userKey: string;
  /**
   * The feature flag key
   */
  featureFlagKey: string;
};

/** @internal */
export const GetUserFlagSettingRequest$inboundSchema: z.ZodType<
  GetUserFlagSettingRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectKey: z.string(),
  environmentKey: z.string(),
  userKey: z.string(),
  featureFlagKey: z.string(),
});

/** @internal */
export type GetUserFlagSettingRequest$Outbound = {
  projectKey: string;
  environmentKey: string;
  userKey: string;
  featureFlagKey: string;
};

/** @internal */
export const GetUserFlagSettingRequest$outboundSchema: z.ZodType<
  GetUserFlagSettingRequest$Outbound,
  z.ZodTypeDef,
  GetUserFlagSettingRequest
> = z.object({
  projectKey: z.string(),
  environmentKey: z.string(),
  userKey: z.string(),
  featureFlagKey: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUserFlagSettingRequest$ {
  /** @deprecated use `GetUserFlagSettingRequest$inboundSchema` instead. */
  export const inboundSchema = GetUserFlagSettingRequest$inboundSchema;
  /** @deprecated use `GetUserFlagSettingRequest$outboundSchema` instead. */
  export const outboundSchema = GetUserFlagSettingRequest$outboundSchema;
  /** @deprecated use `GetUserFlagSettingRequest$Outbound` instead. */
  export type Outbound = GetUserFlagSettingRequest$Outbound;
}

export function getUserFlagSettingRequestToJSON(
  getUserFlagSettingRequest: GetUserFlagSettingRequest,
): string {
  return JSON.stringify(
    GetUserFlagSettingRequest$outboundSchema.parse(getUserFlagSettingRequest),
  );
}

export function getUserFlagSettingRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetUserFlagSettingRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserFlagSettingRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserFlagSettingRequest' from JSON`,
  );
}
