/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PatchFlagImportConfigurationRequest = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The integration key
   */
  integrationKey: string;
  /**
   * The integration ID
   */
  integrationId: string;
  requestBody: Array<components.PatchOperation>;
};

/** @internal */
export const PatchFlagImportConfigurationRequest$inboundSchema: z.ZodType<
  PatchFlagImportConfigurationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectKey: z.string(),
  integrationKey: z.string(),
  integrationId: z.string(),
  RequestBody: z.array(components.PatchOperation$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type PatchFlagImportConfigurationRequest$Outbound = {
  projectKey: string;
  integrationKey: string;
  integrationId: string;
  RequestBody: Array<components.PatchOperation$Outbound>;
};

/** @internal */
export const PatchFlagImportConfigurationRequest$outboundSchema: z.ZodType<
  PatchFlagImportConfigurationRequest$Outbound,
  z.ZodTypeDef,
  PatchFlagImportConfigurationRequest
> = z.object({
  projectKey: z.string(),
  integrationKey: z.string(),
  integrationId: z.string(),
  requestBody: z.array(components.PatchOperation$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchFlagImportConfigurationRequest$ {
  /** @deprecated use `PatchFlagImportConfigurationRequest$inboundSchema` instead. */
  export const inboundSchema =
    PatchFlagImportConfigurationRequest$inboundSchema;
  /** @deprecated use `PatchFlagImportConfigurationRequest$outboundSchema` instead. */
  export const outboundSchema =
    PatchFlagImportConfigurationRequest$outboundSchema;
  /** @deprecated use `PatchFlagImportConfigurationRequest$Outbound` instead. */
  export type Outbound = PatchFlagImportConfigurationRequest$Outbound;
}

export function patchFlagImportConfigurationRequestToJSON(
  patchFlagImportConfigurationRequest: PatchFlagImportConfigurationRequest,
): string {
  return JSON.stringify(
    PatchFlagImportConfigurationRequest$outboundSchema.parse(
      patchFlagImportConfigurationRequest,
    ),
  );
}

export function patchFlagImportConfigurationRequestFromJSON(
  jsonString: string,
): SafeParseResult<PatchFlagImportConfigurationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PatchFlagImportConfigurationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchFlagImportConfigurationRequest' from JSON`,
  );
}
