/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PatchFlagConfigApprovalRequestRequest = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The feature flag key
   */
  featureFlagKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * The approval ID
   */
  id: string;
};

/** @internal */
export const PatchFlagConfigApprovalRequestRequest$inboundSchema: z.ZodType<
  PatchFlagConfigApprovalRequestRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectKey: z.string(),
  featureFlagKey: z.string(),
  environmentKey: z.string(),
  id: z.string(),
});

/** @internal */
export type PatchFlagConfigApprovalRequestRequest$Outbound = {
  projectKey: string;
  featureFlagKey: string;
  environmentKey: string;
  id: string;
};

/** @internal */
export const PatchFlagConfigApprovalRequestRequest$outboundSchema: z.ZodType<
  PatchFlagConfigApprovalRequestRequest$Outbound,
  z.ZodTypeDef,
  PatchFlagConfigApprovalRequestRequest
> = z.object({
  projectKey: z.string(),
  featureFlagKey: z.string(),
  environmentKey: z.string(),
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchFlagConfigApprovalRequestRequest$ {
  /** @deprecated use `PatchFlagConfigApprovalRequestRequest$inboundSchema` instead. */
  export const inboundSchema =
    PatchFlagConfigApprovalRequestRequest$inboundSchema;
  /** @deprecated use `PatchFlagConfigApprovalRequestRequest$outboundSchema` instead. */
  export const outboundSchema =
    PatchFlagConfigApprovalRequestRequest$outboundSchema;
  /** @deprecated use `PatchFlagConfigApprovalRequestRequest$Outbound` instead. */
  export type Outbound = PatchFlagConfigApprovalRequestRequest$Outbound;
}

export function patchFlagConfigApprovalRequestRequestToJSON(
  patchFlagConfigApprovalRequestRequest: PatchFlagConfigApprovalRequestRequest,
): string {
  return JSON.stringify(
    PatchFlagConfigApprovalRequestRequest$outboundSchema.parse(
      patchFlagConfigApprovalRequestRequest,
    ),
  );
}

export function patchFlagConfigApprovalRequestRequestFromJSON(
  jsonString: string,
): SafeParseResult<PatchFlagConfigApprovalRequestRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PatchFlagConfigApprovalRequestRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchFlagConfigApprovalRequestRequest' from JSON`,
  );
}
