/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PatchExpiringFlagsForUserRequest = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The user key
   */
  userKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  patchUsersRequest: models.PatchUsersRequest;
};

/** @internal */
export const PatchExpiringFlagsForUserRequest$inboundSchema: z.ZodType<
  PatchExpiringFlagsForUserRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectKey: z.string(),
  userKey: z.string(),
  environmentKey: z.string(),
  patchUsersRequest: models.PatchUsersRequest$inboundSchema,
});

/** @internal */
export type PatchExpiringFlagsForUserRequest$Outbound = {
  projectKey: string;
  userKey: string;
  environmentKey: string;
  patchUsersRequest: models.PatchUsersRequest$Outbound;
};

/** @internal */
export const PatchExpiringFlagsForUserRequest$outboundSchema: z.ZodType<
  PatchExpiringFlagsForUserRequest$Outbound,
  z.ZodTypeDef,
  PatchExpiringFlagsForUserRequest
> = z.object({
  projectKey: z.string(),
  userKey: z.string(),
  environmentKey: z.string(),
  patchUsersRequest: models.PatchUsersRequest$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchExpiringFlagsForUserRequest$ {
  /** @deprecated use `PatchExpiringFlagsForUserRequest$inboundSchema` instead. */
  export const inboundSchema = PatchExpiringFlagsForUserRequest$inboundSchema;
  /** @deprecated use `PatchExpiringFlagsForUserRequest$outboundSchema` instead. */
  export const outboundSchema = PatchExpiringFlagsForUserRequest$outboundSchema;
  /** @deprecated use `PatchExpiringFlagsForUserRequest$Outbound` instead. */
  export type Outbound = PatchExpiringFlagsForUserRequest$Outbound;
}

export function patchExpiringFlagsForUserRequestToJSON(
  patchExpiringFlagsForUserRequest: PatchExpiringFlagsForUserRequest,
): string {
  return JSON.stringify(
    PatchExpiringFlagsForUserRequest$outboundSchema.parse(
      patchExpiringFlagsForUserRequest,
    ),
  );
}

export function patchExpiringFlagsForUserRequestFromJSON(
  jsonString: string,
): SafeParseResult<PatchExpiringFlagsForUserRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchExpiringFlagsForUserRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchExpiringFlagsForUserRequest' from JSON`,
  );
}
