/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PatchMetricRequest = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The metric key
   */
  metricKey: string;
  requestBody: Array<models.PatchOperation>;
};

/** @internal */
export const PatchMetricRequest$inboundSchema: z.ZodType<
  PatchMetricRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectKey: z.string(),
  metricKey: z.string(),
  RequestBody: z.array(models.PatchOperation$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type PatchMetricRequest$Outbound = {
  projectKey: string;
  metricKey: string;
  RequestBody: Array<models.PatchOperation$Outbound>;
};

/** @internal */
export const PatchMetricRequest$outboundSchema: z.ZodType<
  PatchMetricRequest$Outbound,
  z.ZodTypeDef,
  PatchMetricRequest
> = z.object({
  projectKey: z.string(),
  metricKey: z.string(),
  requestBody: z.array(models.PatchOperation$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchMetricRequest$ {
  /** @deprecated use `PatchMetricRequest$inboundSchema` instead. */
  export const inboundSchema = PatchMetricRequest$inboundSchema;
  /** @deprecated use `PatchMetricRequest$outboundSchema` instead. */
  export const outboundSchema = PatchMetricRequest$outboundSchema;
  /** @deprecated use `PatchMetricRequest$Outbound` instead. */
  export type Outbound = PatchMetricRequest$Outbound;
}

export function patchMetricRequestToJSON(
  patchMetricRequest: PatchMetricRequest,
): string {
  return JSON.stringify(
    PatchMetricRequest$outboundSchema.parse(patchMetricRequest),
  );
}

export function patchMetricRequestFromJSON(
  jsonString: string,
): SafeParseResult<PatchMetricRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchMetricRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchMetricRequest' from JSON`,
  );
}
