/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PostFlagCopyConfigApprovalRequestRequest = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The feature flag key
   */
  featureFlagKey: string;
  /**
   * The environment key for the target environment
   */
  environmentKey: string;
  createCopyFlagConfigApprovalRequestRequest:
    models.CreateCopyFlagConfigApprovalRequestRequest;
};

/** @internal */
export const PostFlagCopyConfigApprovalRequestRequest$inboundSchema: z.ZodType<
  PostFlagCopyConfigApprovalRequestRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectKey: z.string(),
  featureFlagKey: z.string(),
  environmentKey: z.string(),
  createCopyFlagConfigApprovalRequestRequest:
    models.CreateCopyFlagConfigApprovalRequestRequest$inboundSchema,
});

/** @internal */
export type PostFlagCopyConfigApprovalRequestRequest$Outbound = {
  projectKey: string;
  featureFlagKey: string;
  environmentKey: string;
  createCopyFlagConfigApprovalRequestRequest:
    models.CreateCopyFlagConfigApprovalRequestRequest$Outbound;
};

/** @internal */
export const PostFlagCopyConfigApprovalRequestRequest$outboundSchema: z.ZodType<
  PostFlagCopyConfigApprovalRequestRequest$Outbound,
  z.ZodTypeDef,
  PostFlagCopyConfigApprovalRequestRequest
> = z.object({
  projectKey: z.string(),
  featureFlagKey: z.string(),
  environmentKey: z.string(),
  createCopyFlagConfigApprovalRequestRequest:
    models.CreateCopyFlagConfigApprovalRequestRequest$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostFlagCopyConfigApprovalRequestRequest$ {
  /** @deprecated use `PostFlagCopyConfigApprovalRequestRequest$inboundSchema` instead. */
  export const inboundSchema =
    PostFlagCopyConfigApprovalRequestRequest$inboundSchema;
  /** @deprecated use `PostFlagCopyConfigApprovalRequestRequest$outboundSchema` instead. */
  export const outboundSchema =
    PostFlagCopyConfigApprovalRequestRequest$outboundSchema;
  /** @deprecated use `PostFlagCopyConfigApprovalRequestRequest$Outbound` instead. */
  export type Outbound = PostFlagCopyConfigApprovalRequestRequest$Outbound;
}

export function postFlagCopyConfigApprovalRequestRequestToJSON(
  postFlagCopyConfigApprovalRequestRequest:
    PostFlagCopyConfigApprovalRequestRequest,
): string {
  return JSON.stringify(
    PostFlagCopyConfigApprovalRequestRequest$outboundSchema.parse(
      postFlagCopyConfigApprovalRequestRequest,
    ),
  );
}

export function postFlagCopyConfigApprovalRequestRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  PostFlagCopyConfigApprovalRequestRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostFlagCopyConfigApprovalRequestRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostFlagCopyConfigApprovalRequestRequest' from JSON`,
  );
}
