/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ResetEnvironmentMobileKeyRequest = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
};

/** @internal */
export const ResetEnvironmentMobileKeyRequest$inboundSchema: z.ZodType<
  ResetEnvironmentMobileKeyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectKey: z.string(),
  environmentKey: z.string(),
});

/** @internal */
export type ResetEnvironmentMobileKeyRequest$Outbound = {
  projectKey: string;
  environmentKey: string;
};

/** @internal */
export const ResetEnvironmentMobileKeyRequest$outboundSchema: z.ZodType<
  ResetEnvironmentMobileKeyRequest$Outbound,
  z.ZodTypeDef,
  ResetEnvironmentMobileKeyRequest
> = z.object({
  projectKey: z.string(),
  environmentKey: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResetEnvironmentMobileKeyRequest$ {
  /** @deprecated use `ResetEnvironmentMobileKeyRequest$inboundSchema` instead. */
  export const inboundSchema = ResetEnvironmentMobileKeyRequest$inboundSchema;
  /** @deprecated use `ResetEnvironmentMobileKeyRequest$outboundSchema` instead. */
  export const outboundSchema = ResetEnvironmentMobileKeyRequest$outboundSchema;
  /** @deprecated use `ResetEnvironmentMobileKeyRequest$Outbound` instead. */
  export type Outbound = ResetEnvironmentMobileKeyRequest$Outbound;
}

export function resetEnvironmentMobileKeyRequestToJSON(
  resetEnvironmentMobileKeyRequest: ResetEnvironmentMobileKeyRequest,
): string {
  return JSON.stringify(
    ResetEnvironmentMobileKeyRequest$outboundSchema.parse(
      resetEnvironmentMobileKeyRequest,
    ),
  );
}

export function resetEnvironmentMobileKeyRequestFromJSON(
  jsonString: string,
): SafeParseResult<ResetEnvironmentMobileKeyRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResetEnvironmentMobileKeyRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResetEnvironmentMobileKeyRequest' from JSON`,
  );
}
