/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateAnnouncementPublicRequest = {
  announcementId: string;
  /**
   * Update announcement request body
   */
  requestBody: Array<components.AnnouncementPatchOperation>;
};

/** @internal */
export const UpdateAnnouncementPublicRequest$inboundSchema: z.ZodType<
  UpdateAnnouncementPublicRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  announcementId: z.string(),
  RequestBody: z.array(components.AnnouncementPatchOperation$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateAnnouncementPublicRequest$Outbound = {
  announcementId: string;
  RequestBody: Array<components.AnnouncementPatchOperation$Outbound>;
};

/** @internal */
export const UpdateAnnouncementPublicRequest$outboundSchema: z.ZodType<
  UpdateAnnouncementPublicRequest$Outbound,
  z.ZodTypeDef,
  UpdateAnnouncementPublicRequest
> = z.object({
  announcementId: z.string(),
  requestBody: z.array(components.AnnouncementPatchOperation$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAnnouncementPublicRequest$ {
  /** @deprecated use `UpdateAnnouncementPublicRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateAnnouncementPublicRequest$inboundSchema;
  /** @deprecated use `UpdateAnnouncementPublicRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateAnnouncementPublicRequest$outboundSchema;
  /** @deprecated use `UpdateAnnouncementPublicRequest$Outbound` instead. */
  export type Outbound = UpdateAnnouncementPublicRequest$Outbound;
}

export function updateAnnouncementPublicRequestToJSON(
  updateAnnouncementPublicRequest: UpdateAnnouncementPublicRequest,
): string {
  return JSON.stringify(
    UpdateAnnouncementPublicRequest$outboundSchema.parse(
      updateAnnouncementPublicRequest,
    ),
  );
}

export function updateAnnouncementPublicRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateAnnouncementPublicRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateAnnouncementPublicRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateAnnouncementPublicRequest' from JSON`,
  );
}
