/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Access,
  Access$inboundSchema,
  Access$Outbound,
  Access$outboundSchema,
} from "./access.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Link,
  Link$inboundSchema,
  Link$Outbound,
  Link$outboundSchema,
} from "./link.js";

export type ContextInstanceRecord = {
  /**
   * Timestamp of the last time an evaluation occurred for this context instance
   */
  lastSeen?: Date | undefined;
  /**
   * The context instance ID
   */
  id: string;
  /**
   * An identifier representing the application where the LaunchDarkly SDK is running
   */
  applicationId?: string | undefined;
  /**
   * A list of the context kinds this context was associated with that the SDK removed because they were marked as anonymous at flag evaluation
   */
  anonymousKinds?: Array<string> | undefined;
  /**
   * The context, including its kind and attributes
   */
  context?: any | undefined;
  /**
   * The location and content type of related resources
   */
  links?: { [k: string]: Link } | undefined;
  access?: Access | undefined;
};

/** @internal */
export const ContextInstanceRecord$inboundSchema: z.ZodType<
  ContextInstanceRecord,
  z.ZodTypeDef,
  unknown
> = z.object({
  lastSeen: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  id: z.string(),
  applicationId: z.string().optional(),
  anonymousKinds: z.array(z.string()).optional(),
  context: z.any().optional(),
  _links: z.record(Link$inboundSchema).optional(),
  _access: Access$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "_links": "links",
    "_access": "access",
  });
});

/** @internal */
export type ContextInstanceRecord$Outbound = {
  lastSeen?: string | undefined;
  id: string;
  applicationId?: string | undefined;
  anonymousKinds?: Array<string> | undefined;
  context?: any | undefined;
  _links?: { [k: string]: Link$Outbound } | undefined;
  _access?: Access$Outbound | undefined;
};

/** @internal */
export const ContextInstanceRecord$outboundSchema: z.ZodType<
  ContextInstanceRecord$Outbound,
  z.ZodTypeDef,
  ContextInstanceRecord
> = z.object({
  lastSeen: z.date().transform(v => v.toISOString()).optional(),
  id: z.string(),
  applicationId: z.string().optional(),
  anonymousKinds: z.array(z.string()).optional(),
  context: z.any().optional(),
  links: z.record(Link$outboundSchema).optional(),
  access: Access$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    links: "_links",
    access: "_access",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ContextInstanceRecord$ {
  /** @deprecated use `ContextInstanceRecord$inboundSchema` instead. */
  export const inboundSchema = ContextInstanceRecord$inboundSchema;
  /** @deprecated use `ContextInstanceRecord$outboundSchema` instead. */
  export const outboundSchema = ContextInstanceRecord$outboundSchema;
  /** @deprecated use `ContextInstanceRecord$Outbound` instead. */
  export type Outbound = ContextInstanceRecord$Outbound;
}

export function contextInstanceRecordToJSON(
  contextInstanceRecord: ContextInstanceRecord,
): string {
  return JSON.stringify(
    ContextInstanceRecord$outboundSchema.parse(contextInstanceRecord),
  );
}

export function contextInstanceRecordFromJSON(
  jsonString: string,
): SafeParseResult<ContextInstanceRecord, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContextInstanceRecord$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContextInstanceRecord' from JSON`,
  );
}
