/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ExpiringUserTargetItem,
  ExpiringUserTargetItem$inboundSchema,
  ExpiringUserTargetItem$Outbound,
  ExpiringUserTargetItem$outboundSchema,
} from "./expiringusertargetitem.js";
import {
  Link,
  Link$inboundSchema,
  Link$Outbound,
  Link$outboundSchema,
} from "./link.js";

export type ExpiringUserTargetGetResponse = {
  /**
   * An array of expiring user targets
   */
  items: Array<ExpiringUserTargetItem>;
  /**
   * The location and content type of related resources
   */
  links?: { [k: string]: Link } | undefined;
};

/** @internal */
export const ExpiringUserTargetGetResponse$inboundSchema: z.ZodType<
  ExpiringUserTargetGetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(ExpiringUserTargetItem$inboundSchema),
  _links: z.record(Link$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "_links": "links",
  });
});

/** @internal */
export type ExpiringUserTargetGetResponse$Outbound = {
  items: Array<ExpiringUserTargetItem$Outbound>;
  _links?: { [k: string]: Link$Outbound } | undefined;
};

/** @internal */
export const ExpiringUserTargetGetResponse$outboundSchema: z.ZodType<
  ExpiringUserTargetGetResponse$Outbound,
  z.ZodTypeDef,
  ExpiringUserTargetGetResponse
> = z.object({
  items: z.array(ExpiringUserTargetItem$outboundSchema),
  links: z.record(Link$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    links: "_links",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExpiringUserTargetGetResponse$ {
  /** @deprecated use `ExpiringUserTargetGetResponse$inboundSchema` instead. */
  export const inboundSchema = ExpiringUserTargetGetResponse$inboundSchema;
  /** @deprecated use `ExpiringUserTargetGetResponse$outboundSchema` instead. */
  export const outboundSchema = ExpiringUserTargetGetResponse$outboundSchema;
  /** @deprecated use `ExpiringUserTargetGetResponse$Outbound` instead. */
  export type Outbound = ExpiringUserTargetGetResponse$Outbound;
}

export function expiringUserTargetGetResponseToJSON(
  expiringUserTargetGetResponse: ExpiringUserTargetGetResponse,
): string {
  return JSON.stringify(
    ExpiringUserTargetGetResponse$outboundSchema.parse(
      expiringUserTargetGetResponse,
    ),
  );
}

export function expiringUserTargetGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<ExpiringUserTargetGetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExpiringUserTargetGetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExpiringUserTargetGetResponse' from JSON`,
  );
}
