/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type TeamPatchInput = {
  /**
   * Optional comment describing the update
   */
  comment?: string | undefined;
  instructions: Array<{ [k: string]: any }>;
};

/** @internal */
export const TeamPatchInput$inboundSchema: z.ZodType<
  TeamPatchInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  comment: z.string().optional(),
  instructions: z.array(z.record(z.any())),
});

/** @internal */
export type TeamPatchInput$Outbound = {
  comment?: string | undefined;
  instructions: Array<{ [k: string]: any }>;
};

/** @internal */
export const TeamPatchInput$outboundSchema: z.ZodType<
  TeamPatchInput$Outbound,
  z.ZodTypeDef,
  TeamPatchInput
> = z.object({
  comment: z.string().optional(),
  instructions: z.array(z.record(z.any())),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TeamPatchInput$ {
  /** @deprecated use `TeamPatchInput$inboundSchema` instead. */
  export const inboundSchema = TeamPatchInput$inboundSchema;
  /** @deprecated use `TeamPatchInput$outboundSchema` instead. */
  export const outboundSchema = TeamPatchInput$outboundSchema;
  /** @deprecated use `TeamPatchInput$Outbound` instead. */
  export type Outbound = TeamPatchInput$Outbound;
}

export function teamPatchInputToJSON(teamPatchInput: TeamPatchInput): string {
  return JSON.stringify(TeamPatchInput$outboundSchema.parse(teamPatchInput));
}

export function teamPatchInputFromJSON(
  jsonString: string,
): SafeParseResult<TeamPatchInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TeamPatchInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TeamPatchInput' from JSON`,
  );
}
