/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type TeamsPatchInput = {
  /**
   * Optional comment describing the update
   */
  comment?: string | undefined;
  instructions: Array<{ [k: string]: any }>;
};

/** @internal */
export const TeamsPatchInput$inboundSchema: z.ZodType<
  TeamsPatchInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  comment: z.string().optional(),
  instructions: z.array(z.record(z.any())),
});

/** @internal */
export type TeamsPatchInput$Outbound = {
  comment?: string | undefined;
  instructions: Array<{ [k: string]: any }>;
};

/** @internal */
export const TeamsPatchInput$outboundSchema: z.ZodType<
  TeamsPatchInput$Outbound,
  z.ZodTypeDef,
  TeamsPatchInput
> = z.object({
  comment: z.string().optional(),
  instructions: z.array(z.record(z.any())),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TeamsPatchInput$ {
  /** @deprecated use `TeamsPatchInput$inboundSchema` instead. */
  export const inboundSchema = TeamsPatchInput$inboundSchema;
  /** @deprecated use `TeamsPatchInput$outboundSchema` instead. */
  export const outboundSchema = TeamsPatchInput$outboundSchema;
  /** @deprecated use `TeamsPatchInput$Outbound` instead. */
  export type Outbound = TeamsPatchInput$Outbound;
}

export function teamsPatchInputToJSON(
  teamsPatchInput: TeamsPatchInput,
): string {
  return JSON.stringify(TeamsPatchInput$outboundSchema.parse(teamsPatchInput));
}

export function teamsPatchInputFromJSON(
  jsonString: string,
): SafeParseResult<TeamsPatchInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TeamsPatchInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TeamsPatchInput' from JSON`,
  );
}
