/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CustomRole,
  CustomRole$inboundSchema,
  CustomRole$Outbound,
  CustomRole$outboundSchema,
} from "./customrole.js";
import {
  Link,
  Link$inboundSchema,
  Link$Outbound,
  Link$outboundSchema,
} from "./link.js";

export type CustomRoles = {
  /**
   * The location and content type of related resources
   */
  links?: { [k: string]: Link } | undefined;
  /**
   * An array of custom roles
   */
  items: Array<CustomRole>;
  /**
   * The total number of custom roles
   */
  totalCount?: number | undefined;
};

/** @internal */
export const CustomRoles$inboundSchema: z.ZodType<
  CustomRoles,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.record(Link$inboundSchema).optional(),
  items: z.array(CustomRole$inboundSchema),
  totalCount: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "_links": "links",
  });
});

/** @internal */
export type CustomRoles$Outbound = {
  _links?: { [k: string]: Link$Outbound } | undefined;
  items: Array<CustomRole$Outbound>;
  totalCount?: number | undefined;
};

/** @internal */
export const CustomRoles$outboundSchema: z.ZodType<
  CustomRoles$Outbound,
  z.ZodTypeDef,
  CustomRoles
> = z.object({
  links: z.record(Link$outboundSchema).optional(),
  items: z.array(CustomRole$outboundSchema),
  totalCount: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    links: "_links",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomRoles$ {
  /** @deprecated use `CustomRoles$inboundSchema` instead. */
  export const inboundSchema = CustomRoles$inboundSchema;
  /** @deprecated use `CustomRoles$outboundSchema` instead. */
  export const outboundSchema = CustomRoles$outboundSchema;
  /** @deprecated use `CustomRoles$Outbound` instead. */
  export type Outbound = CustomRoles$Outbound;
}

export function customRolesToJSON(customRoles: CustomRoles): string {
  return JSON.stringify(CustomRoles$outboundSchema.parse(customRoles));
}

export function customRolesFromJSON(
  jsonString: string,
): SafeParseResult<CustomRoles, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomRoles$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomRoles' from JSON`,
  );
}
