/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FeatureFlagScheduledChange,
  FeatureFlagScheduledChange$inboundSchema,
  FeatureFlagScheduledChange$Outbound,
  FeatureFlagScheduledChange$outboundSchema,
} from "./featureflagscheduledchange.js";
import {
  Link,
  Link$inboundSchema,
  Link$Outbound,
  Link$outboundSchema,
} from "./link.js";

export type FeatureFlagScheduledChanges = {
  /**
   * Array of scheduled changes
   */
  items: Array<FeatureFlagScheduledChange>;
  /**
   * The location and content type of related resources
   */
  links?: { [k: string]: Link } | undefined;
};

/** @internal */
export const FeatureFlagScheduledChanges$inboundSchema: z.ZodType<
  FeatureFlagScheduledChanges,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(FeatureFlagScheduledChange$inboundSchema),
  _links: z.record(Link$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "_links": "links",
  });
});

/** @internal */
export type FeatureFlagScheduledChanges$Outbound = {
  items: Array<FeatureFlagScheduledChange$Outbound>;
  _links?: { [k: string]: Link$Outbound } | undefined;
};

/** @internal */
export const FeatureFlagScheduledChanges$outboundSchema: z.ZodType<
  FeatureFlagScheduledChanges$Outbound,
  z.ZodTypeDef,
  FeatureFlagScheduledChanges
> = z.object({
  items: z.array(FeatureFlagScheduledChange$outboundSchema),
  links: z.record(Link$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    links: "_links",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FeatureFlagScheduledChanges$ {
  /** @deprecated use `FeatureFlagScheduledChanges$inboundSchema` instead. */
  export const inboundSchema = FeatureFlagScheduledChanges$inboundSchema;
  /** @deprecated use `FeatureFlagScheduledChanges$outboundSchema` instead. */
  export const outboundSchema = FeatureFlagScheduledChanges$outboundSchema;
  /** @deprecated use `FeatureFlagScheduledChanges$Outbound` instead. */
  export type Outbound = FeatureFlagScheduledChanges$Outbound;
}

export function featureFlagScheduledChangesToJSON(
  featureFlagScheduledChanges: FeatureFlagScheduledChanges,
): string {
  return JSON.stringify(
    FeatureFlagScheduledChanges$outboundSchema.parse(
      featureFlagScheduledChanges,
    ),
  );
}

export function featureFlagScheduledChangesFromJSON(
  jsonString: string,
): SafeParseResult<FeatureFlagScheduledChanges, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FeatureFlagScheduledChanges$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FeatureFlagScheduledChanges' from JSON`,
  );
}
