/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type HoldoutPatchInput = {
  /**
   * Optional comment describing the update
   */
  comment?: string | undefined;
  instructions: Array<{ [k: string]: any }>;
};

/** @internal */
export const HoldoutPatchInput$inboundSchema: z.ZodType<
  HoldoutPatchInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  comment: z.string().optional(),
  instructions: z.array(z.record(z.any())),
});

/** @internal */
export type HoldoutPatchInput$Outbound = {
  comment?: string | undefined;
  instructions: Array<{ [k: string]: any }>;
};

/** @internal */
export const HoldoutPatchInput$outboundSchema: z.ZodType<
  HoldoutPatchInput$Outbound,
  z.ZodTypeDef,
  HoldoutPatchInput
> = z.object({
  comment: z.string().optional(),
  instructions: z.array(z.record(z.any())),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace HoldoutPatchInput$ {
  /** @deprecated use `HoldoutPatchInput$inboundSchema` instead. */
  export const inboundSchema = HoldoutPatchInput$inboundSchema;
  /** @deprecated use `HoldoutPatchInput$outboundSchema` instead. */
  export const outboundSchema = HoldoutPatchInput$outboundSchema;
  /** @deprecated use `HoldoutPatchInput$Outbound` instead. */
  export type Outbound = HoldoutPatchInput$Outbound;
}

export function holdoutPatchInputToJSON(
  holdoutPatchInput: HoldoutPatchInput,
): string {
  return JSON.stringify(
    HoldoutPatchInput$outboundSchema.parse(holdoutPatchInput),
  );
}

export function holdoutPatchInputFromJSON(
  jsonString: string,
): SafeParseResult<HoldoutPatchInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HoldoutPatchInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HoldoutPatchInput' from JSON`,
  );
}
