/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Link,
  Link$inboundSchema,
  Link$Outbound,
  Link$outboundSchema,
} from "./link.js";

export type IntegrationDeliveryConfigurationLinks = {
  self: Link;
  parent: Link;
  project: Link;
  environment: Link;
};

/** @internal */
export const IntegrationDeliveryConfigurationLinks$inboundSchema: z.ZodType<
  IntegrationDeliveryConfigurationLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: Link$inboundSchema,
  parent: Link$inboundSchema,
  project: Link$inboundSchema,
  environment: Link$inboundSchema,
});

/** @internal */
export type IntegrationDeliveryConfigurationLinks$Outbound = {
  self: Link$Outbound;
  parent: Link$Outbound;
  project: Link$Outbound;
  environment: Link$Outbound;
};

/** @internal */
export const IntegrationDeliveryConfigurationLinks$outboundSchema: z.ZodType<
  IntegrationDeliveryConfigurationLinks$Outbound,
  z.ZodTypeDef,
  IntegrationDeliveryConfigurationLinks
> = z.object({
  self: Link$outboundSchema,
  parent: Link$outboundSchema,
  project: Link$outboundSchema,
  environment: Link$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IntegrationDeliveryConfigurationLinks$ {
  /** @deprecated use `IntegrationDeliveryConfigurationLinks$inboundSchema` instead. */
  export const inboundSchema =
    IntegrationDeliveryConfigurationLinks$inboundSchema;
  /** @deprecated use `IntegrationDeliveryConfigurationLinks$outboundSchema` instead. */
  export const outboundSchema =
    IntegrationDeliveryConfigurationLinks$outboundSchema;
  /** @deprecated use `IntegrationDeliveryConfigurationLinks$Outbound` instead. */
  export type Outbound = IntegrationDeliveryConfigurationLinks$Outbound;
}

export function integrationDeliveryConfigurationLinksToJSON(
  integrationDeliveryConfigurationLinks: IntegrationDeliveryConfigurationLinks,
): string {
  return JSON.stringify(
    IntegrationDeliveryConfigurationLinks$outboundSchema.parse(
      integrationDeliveryConfigurationLinks,
    ),
  );
}

export function integrationDeliveryConfigurationLinksFromJSON(
  jsonString: string,
): SafeParseResult<IntegrationDeliveryConfigurationLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      IntegrationDeliveryConfigurationLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IntegrationDeliveryConfigurationLinks' from JSON`,
  );
}
