/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Access,
  Access$inboundSchema,
  Access$Outbound,
  Access$outboundSchema,
} from "./access.js";
import {
  Filter,
  Filter$inboundSchema,
  Filter$Outbound,
  Filter$outboundSchema,
} from "./filter.js";
import {
  Link,
  Link$inboundSchema,
  Link$Outbound,
  Link$outboundSchema,
} from "./link.js";
import {
  MemberSummary,
  MemberSummary$inboundSchema,
  MemberSummary$Outbound,
  MemberSummary$outboundSchema,
} from "./membersummary.js";
import {
  MetricEventDefaultRep,
  MetricEventDefaultRep$inboundSchema,
  MetricEventDefaultRep$Outbound,
  MetricEventDefaultRep$outboundSchema,
} from "./metriceventdefaultrep.js";
import {
  Modification,
  Modification$inboundSchema,
  Modification$Outbound,
  Modification$outboundSchema,
} from "./modification.js";

/**
 * The kind of event the metric tracks
 */
export const MetricListingRepKind = {
  Pageview: "pageview",
  Click: "click",
  Custom: "custom",
} as const;
/**
 * The kind of event the metric tracks
 */
export type MetricListingRepKind = ClosedEnum<typeof MetricListingRepKind>;

/**
 * For custom metrics, the success criteria
 */
export const SuccessCriteria = {
  HigherThanBaseline: "HigherThanBaseline",
  LowerThanBaseline: "LowerThanBaseline",
} as const;
/**
 * For custom metrics, the success criteria
 */
export type SuccessCriteria = ClosedEnum<typeof SuccessCriteria>;

/**
 * The method by which multiple unit event values are aggregated
 */
export const UnitAggregationType = {
  Average: "average",
  Sum: "sum",
} as const;
/**
 * The method by which multiple unit event values are aggregated
 */
export type UnitAggregationType = ClosedEnum<typeof UnitAggregationType>;

/**
 * The method for analyzing metric events
 */
export const AnalysisType = {
  Mean: "mean",
  Percentile: "percentile",
} as const;
/**
 * The method for analyzing metric events
 */
export type AnalysisType = ClosedEnum<typeof AnalysisType>;

export type MetricListingRep = {
  /**
   * The number of experiments using this metric
   */
  experimentCount?: number | undefined;
  /**
   * The number of metric groups using this metric
   */
  metricGroupCount?: number | undefined;
  /**
   * The ID of this metric
   */
  id: string;
  /**
   * The version ID of the metric
   */
  versionId: string;
  /**
   * A unique key to reference the metric
   */
  key: string;
  /**
   * A human-friendly name for the metric
   */
  name: string;
  /**
   * The kind of event the metric tracks
   */
  kind: MetricListingRepKind;
  /**
   * The number of feature flags currently attached to this metric
   */
  attachedFlagCount?: number | undefined;
  /**
   * The location and content type of related resources
   */
  links: { [k: string]: Link };
  site?: Link | undefined;
  access?: Access | undefined;
  /**
   * Tags for the metric
   */
  tags: Array<string>;
  creationDate: number;
  lastModified?: Modification | undefined;
  /**
   * The ID of the member who maintains this metric
   */
  maintainerId?: string | undefined;
  maintainer?: MemberSummary | undefined;
  /**
   * Description of the metric
   */
  description?: string | undefined;
  /**
   * The category of the metric
   */
  category?: string | undefined;
  /**
   * For custom metrics, whether to track numeric changes in value against a baseline (<code>true</code>) or to track a conversion when an end user takes an action (<code>false</code>).
   */
  isNumeric?: boolean | undefined;
  /**
   * For custom metrics, the success criteria
   */
  successCriteria?: SuccessCriteria | undefined;
  /**
   * For numeric custom metrics, the unit of measure
   */
  unit?: string | undefined;
  /**
   * For custom metrics, the event key to use in your code
   */
  eventKey?: string | undefined;
  /**
   * An array of randomization units allowed for this metric
   */
  randomizationUnits?: Array<string> | undefined;
  filters?: Filter | undefined;
  /**
   * The method by which multiple unit event values are aggregated
   */
  unitAggregationType?: UnitAggregationType | undefined;
  /**
   * The method for analyzing metric events
   */
  analysisType?: AnalysisType | undefined;
  /**
   * The percentile for the analysis method. An integer denoting the target percentile between 0 and 100. Required when <code>analysisType</code> is <code>percentile</code>.
   */
  percentileValue?: number | undefined;
  eventDefault?: MetricEventDefaultRep | undefined;
};

/** @internal */
export const MetricListingRepKind$inboundSchema: z.ZodNativeEnum<
  typeof MetricListingRepKind
> = z.nativeEnum(MetricListingRepKind);

/** @internal */
export const MetricListingRepKind$outboundSchema: z.ZodNativeEnum<
  typeof MetricListingRepKind
> = MetricListingRepKind$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MetricListingRepKind$ {
  /** @deprecated use `MetricListingRepKind$inboundSchema` instead. */
  export const inboundSchema = MetricListingRepKind$inboundSchema;
  /** @deprecated use `MetricListingRepKind$outboundSchema` instead. */
  export const outboundSchema = MetricListingRepKind$outboundSchema;
}

/** @internal */
export const SuccessCriteria$inboundSchema: z.ZodNativeEnum<
  typeof SuccessCriteria
> = z.nativeEnum(SuccessCriteria);

/** @internal */
export const SuccessCriteria$outboundSchema: z.ZodNativeEnum<
  typeof SuccessCriteria
> = SuccessCriteria$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SuccessCriteria$ {
  /** @deprecated use `SuccessCriteria$inboundSchema` instead. */
  export const inboundSchema = SuccessCriteria$inboundSchema;
  /** @deprecated use `SuccessCriteria$outboundSchema` instead. */
  export const outboundSchema = SuccessCriteria$outboundSchema;
}

/** @internal */
export const UnitAggregationType$inboundSchema: z.ZodNativeEnum<
  typeof UnitAggregationType
> = z.nativeEnum(UnitAggregationType);

/** @internal */
export const UnitAggregationType$outboundSchema: z.ZodNativeEnum<
  typeof UnitAggregationType
> = UnitAggregationType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnitAggregationType$ {
  /** @deprecated use `UnitAggregationType$inboundSchema` instead. */
  export const inboundSchema = UnitAggregationType$inboundSchema;
  /** @deprecated use `UnitAggregationType$outboundSchema` instead. */
  export const outboundSchema = UnitAggregationType$outboundSchema;
}

/** @internal */
export const AnalysisType$inboundSchema: z.ZodNativeEnum<typeof AnalysisType> =
  z.nativeEnum(AnalysisType);

/** @internal */
export const AnalysisType$outboundSchema: z.ZodNativeEnum<typeof AnalysisType> =
  AnalysisType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AnalysisType$ {
  /** @deprecated use `AnalysisType$inboundSchema` instead. */
  export const inboundSchema = AnalysisType$inboundSchema;
  /** @deprecated use `AnalysisType$outboundSchema` instead. */
  export const outboundSchema = AnalysisType$outboundSchema;
}

/** @internal */
export const MetricListingRep$inboundSchema: z.ZodType<
  MetricListingRep,
  z.ZodTypeDef,
  unknown
> = z.object({
  experimentCount: z.number().int().optional(),
  metricGroupCount: z.number().int().optional(),
  _id: z.string(),
  _versionId: z.string(),
  key: z.string(),
  name: z.string(),
  kind: MetricListingRepKind$inboundSchema,
  _attachedFlagCount: z.number().int().optional(),
  _links: z.record(Link$inboundSchema),
  _site: Link$inboundSchema.optional(),
  _access: Access$inboundSchema.optional(),
  tags: z.array(z.string()),
  _creationDate: z.number().int(),
  lastModified: Modification$inboundSchema.optional(),
  maintainerId: z.string().optional(),
  _maintainer: MemberSummary$inboundSchema.optional(),
  description: z.string().optional(),
  category: z.string().optional(),
  isNumeric: z.boolean().optional(),
  successCriteria: SuccessCriteria$inboundSchema.optional(),
  unit: z.string().optional(),
  eventKey: z.string().optional(),
  randomizationUnits: z.array(z.string()).optional(),
  filters: Filter$inboundSchema.optional(),
  unitAggregationType: UnitAggregationType$inboundSchema.optional(),
  analysisType: AnalysisType$inboundSchema.optional(),
  percentileValue: z.number().int().optional(),
  eventDefault: MetricEventDefaultRep$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "_id": "id",
    "_versionId": "versionId",
    "_attachedFlagCount": "attachedFlagCount",
    "_links": "links",
    "_site": "site",
    "_access": "access",
    "_creationDate": "creationDate",
    "_maintainer": "maintainer",
  });
});

/** @internal */
export type MetricListingRep$Outbound = {
  experimentCount?: number | undefined;
  metricGroupCount?: number | undefined;
  _id: string;
  _versionId: string;
  key: string;
  name: string;
  kind: string;
  _attachedFlagCount?: number | undefined;
  _links: { [k: string]: Link$Outbound };
  _site?: Link$Outbound | undefined;
  _access?: Access$Outbound | undefined;
  tags: Array<string>;
  _creationDate: number;
  lastModified?: Modification$Outbound | undefined;
  maintainerId?: string | undefined;
  _maintainer?: MemberSummary$Outbound | undefined;
  description?: string | undefined;
  category?: string | undefined;
  isNumeric?: boolean | undefined;
  successCriteria?: string | undefined;
  unit?: string | undefined;
  eventKey?: string | undefined;
  randomizationUnits?: Array<string> | undefined;
  filters?: Filter$Outbound | undefined;
  unitAggregationType?: string | undefined;
  analysisType?: string | undefined;
  percentileValue?: number | undefined;
  eventDefault?: MetricEventDefaultRep$Outbound | undefined;
};

/** @internal */
export const MetricListingRep$outboundSchema: z.ZodType<
  MetricListingRep$Outbound,
  z.ZodTypeDef,
  MetricListingRep
> = z.object({
  experimentCount: z.number().int().optional(),
  metricGroupCount: z.number().int().optional(),
  id: z.string(),
  versionId: z.string(),
  key: z.string(),
  name: z.string(),
  kind: MetricListingRepKind$outboundSchema,
  attachedFlagCount: z.number().int().optional(),
  links: z.record(Link$outboundSchema),
  site: Link$outboundSchema.optional(),
  access: Access$outboundSchema.optional(),
  tags: z.array(z.string()),
  creationDate: z.number().int(),
  lastModified: Modification$outboundSchema.optional(),
  maintainerId: z.string().optional(),
  maintainer: MemberSummary$outboundSchema.optional(),
  description: z.string().optional(),
  category: z.string().optional(),
  isNumeric: z.boolean().optional(),
  successCriteria: SuccessCriteria$outboundSchema.optional(),
  unit: z.string().optional(),
  eventKey: z.string().optional(),
  randomizationUnits: z.array(z.string()).optional(),
  filters: Filter$outboundSchema.optional(),
  unitAggregationType: UnitAggregationType$outboundSchema.optional(),
  analysisType: AnalysisType$outboundSchema.optional(),
  percentileValue: z.number().int().optional(),
  eventDefault: MetricEventDefaultRep$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    id: "_id",
    versionId: "_versionId",
    attachedFlagCount: "_attachedFlagCount",
    links: "_links",
    site: "_site",
    access: "_access",
    creationDate: "_creationDate",
    maintainer: "_maintainer",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MetricListingRep$ {
  /** @deprecated use `MetricListingRep$inboundSchema` instead. */
  export const inboundSchema = MetricListingRep$inboundSchema;
  /** @deprecated use `MetricListingRep$outboundSchema` instead. */
  export const outboundSchema = MetricListingRep$outboundSchema;
  /** @deprecated use `MetricListingRep$Outbound` instead. */
  export type Outbound = MetricListingRep$Outbound;
}

export function metricListingRepToJSON(
  metricListingRep: MetricListingRep,
): string {
  return JSON.stringify(
    MetricListingRep$outboundSchema.parse(metricListingRep),
  );
}

export function metricListingRepFromJSON(
  jsonString: string,
): SafeParseResult<MetricListingRep, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MetricListingRep$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MetricListingRep' from JSON`,
  );
}
